import { useEffect, useState } from "react";
import api from "../api/axios";
import React from "react";
import Footer from "../components/Footer";
import { Share2 } from "lucide-react";
import jsPDF from "jspdf";

const baseUrl = "http://localhost:5000";

// PDF Generator for Poster (UPDATED)
const generatePosterPDF = async (poster) => {
    const doc = new jsPDF("p", "mm", "a4");
    doc.setFont("helvetica", "normal");

    // Load image
    let imgBase64 = null;
    try {
        const imgResponse = await fetch(`${baseUrl}/${poster.image}`);
        if (!imgResponse.ok) throw new Error("Image not found");
        const imgBlob = await imgResponse.blob();
        imgBase64 = await new Promise((resolve) => {
            const reader = new FileReader();
            reader.onloadend = () => resolve(reader.result);
            reader.readAsDataURL(imgBlob);
        });
    } catch (err) {
        console.error("Error loading image for PDF", err);
    }

    // ===== HEADER =====
    doc.setFillColor(128, 0, 0);
    doc.rect(0, 0, 210, 30, "F"); // Slightly smaller header to give more space
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.text("MYCHITS – PROMOTIONAL POSTER", 105, 18, { align: "center" });

    // ===== IMAGE (LARGE - 3/4 PAGE) =====
    // A4 Height is 297mm. We want the image to be dominant.
    // Header takes 30mm. Let's give image 190mm height (approx 75% of remaining space).
    const imgX = 15; // Margin Left
    const imgY = 35; // Start immediately after header
    const imgWidth = 180; // Full width with margins
    const imgHeight = 190; // INCREASED HEIGHT to fill 3/4 of page

    if (imgBase64) {
        // Adding image
        doc.addImage(imgBase64, "JPEG", imgX, imgY, imgWidth, imgHeight);
        
        // Optional: Subtle border around image
        doc.setDrawColor(200);
        doc.setLineWidth(0.5);
        doc.rect(imgX, imgY, imgWidth, imgHeight);
    }

    // ===== CONTENT (Text below image) =====
    // Text starts after the large image
    let textY = imgY + imgHeight + 10; // 10mm gap after image

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text(poster.title || "Poster", imgX, textY);
    
    // Description
    textY += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(80);
    
    // Clean description text
    const cleanDesc = (poster.description || "").replace(/₹/g, "Rs.");
    const lines = doc.splitTextToSize(cleanDesc, imgWidth); // Match text width to image width
    doc.text(lines, imgX, textY);

    // ===== FOOTER =====
    doc.setFontSize(10);
    doc.setTextColor(120);
    doc.text("Generated by MyChits", 105, 290, { align: "center" });

    doc.save(`MyChits_Poster_${poster.title}.pdf`);
};

export default function ChitPoster() {
    const [posters, setPosters] = useState([]);
    const [showModal, setShowModal] = useState(false);
    const [selectedPoster, setSelectedPoster] = useState(null);
    const [customer, setCustomer] = useState({ name: "", phone: "" });

    useEffect(() => {
        fetchPosters();
    }, []);

    const fetchPosters = async () => {
        try {
            const res = await api.get("/posters");
            setPosters(res.data);
        } catch (err) {
            console.error("Error fetching posters:", err);
        }
    };

    const handleShare = (p) => {
        const shareText = `MyChits Poster: ${p.title}\n\n${p.description}\n\nCheck this out!`;
        if (navigator.share) {
            navigator.share({ title: "MyChits Poster", text: shareText, url: window.location.href });
        } else {
            navigator.clipboard.writeText(shareText);
            alert("Poster details copied to clipboard");
        }
    };

    return (
        <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 text-gray-100 pb-20">
            {/* HEADER */}
            <div className="max-w-7xl mx-auto px-6 py-20 text-center">
                <h1 className="text-5xl md:text-7xl font-extrabold text-white mb-4 tracking-tighter">
                    Poster <span className="text-purple-500">Gallery</span>
                </h1>
                <p className="text-gray-400 text-lg max-w-2xl mx-auto">
                    Browse our latest promotional posters and offers.
                </p>
            </div>

            {/* MASONRY GRID */}
            <div className="max-w-7xl mx-auto px-6">
                <div className="columns-1 md:columns-2 lg:columns-3 gap-6 space-y-6">
                    {posters.map((p) => (
                        <div key={p._id} className="break-inside-avoid relative group rounded-xl overflow-hidden cursor-pointer bg-[#404040] shadow-lg hover:shadow-2xl transition-all duration-300">
                            
                            {/* IMAGE */}
                            <div className="relative w-full h-auto">
                                <img
                                    src={`${baseUrl}/${p.image}`}
                                    alt={p.title}
                                    className="w-full h-auto object-cover transition-transform duration-700 group-hover:scale-105"
                                />

                                {/* Badge */}
                                <span className="absolute top-4 right-4 px-3 py-1 text-xs font-bold uppercase tracking-widest rounded-md shadow-lg bg-purple-600 text-white">
                                    POSTER
                                </span>

                                {/* Overlay */}
                                <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/50 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex flex-col justify-end p-6">
                                    
                                    <h3 className="text-3xl font-bold text-white mb-1 translate-y-4 group-hover:translate-y-0 transition-transform duration-300">
                                        {p.title}
                                    </h3>

                                    <p className="text-gray-300 text-sm line-clamp-2 mb-4">
                                        {p.description}
                                    </p>

                                    <div className="flex items-center justify-between">
                                        <div className="flex gap-2">
                                            <button
                                                onClick={(e) => { e.stopPropagation(); handleShare(p); }}
                                                className="bg-white/20 backdrop-blur p-2 rounded-full hover:bg-white/40 transition"
                                            >
                                                <Share2 size={16} />
                                            </button>
                                        </div>

                                        <button
                                            onClick={(e) => {
                                                e.stopPropagation();
                                                setSelectedPoster(p);
                                                setShowModal(true);
                                            }}
                                            className="bg-white text-black p-2 rounded-full hover:bg-purple-400 transition-colors"
                                            title="Download / Info"
                                        >
                                            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                                            </svg>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            {posters.length === 0 && (
                <div className="text-center py-20 text-gray-500">
                    <p className="text-lg">No posters available yet.</p>
                </div>
            )}

            {/* MODAL */}
            {showModal && selectedPoster && (
                <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 px-4">
                    <div className="bg-white rounded-2xl shadow-2xl w-full max-w-3xl overflow-hidden grid grid-cols-1 md:grid-cols-2">
                        
                        {/* Left Side */}
                        <div className="bg-gradient-to-br from-purple-600 to-purple-500 text-white p-8 flex flex-col justify-between">
                            <div>
                                <h2 className="text-3xl font-extrabold mb-3">
                                    My<span className="text-yellow-300">Chits</span>
                                </h2>
                                <p className="text-purple-100 mb-6">Exclusive offers and promotional updates.</p>
                                
                                <div className="bg-white/10 rounded-xl p-4 space-y-2">
                                    <p className="text-sm text-purple-100">Selected Poster</p>
                                    <h3 className="text-2xl font-bold">{selectedPoster.title}</h3>
                                    <p className="text-xs text-purple-200 mt-2">{selectedPoster.description}</p>
                                </div>
                            </div>
                        </div>

                        {/* Right Side - Form */}
                        <div className="p-8 text-black">
                            <h3 className="text-2xl font-bold mb-2">Download Poster</h3>
                            <p className="text-gray-500 text-sm mb-6">Enter details to download the poster PDF</p>

                            <input
                                type="text" placeholder="Your Name"
                                className="w-full border border-gray-300 p-3 rounded-lg mb-4 focus:outline-none focus:ring-2 focus:ring-purple-500"
                                value={customer.name}
                                onChange={(e) => setCustomer({ ...customer, name: e.target.value })}
                            />
                            <input
                                type="tel" placeholder="Phone Number"
                                className="w-full border border-gray-300 p-3 rounded-lg mb-6 focus:outline-none focus:ring-2 focus:ring-purple-500"
                                value={customer.phone}
                                onChange={(e) => setCustomer({ ...customer, phone: e.target.value })}
                            />

                            <div className="flex gap-3">
                                <button onClick={() => setShowModal(false)} className="w-1/2 py-3 rounded-lg bg-gray-200 hover:bg-gray-300 transition">Cancel</button>
                                <button
                                    onClick={async () => {
                                        if (!customer.name || !customer.phone) { alert("Please enter details"); return; }
                                        try {
                                            await generatePosterPDF(selectedPoster);
                                            setCustomer({ name: "", phone: "" });
                                            setShowModal(false);
                                        } catch (err) {
                                            console.error(err);
                                            alert("Failed");
                                        }
                                    }}
                                    className="w-1/2 py-3 rounded-lg bg-purple-600 text-white font-semibold hover:bg-purple-700 transition"
                                >
                                    Download PDF
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}