import { useEffect, useState } from "react";
import api from "../api/axios";
import React from "react";
import Footer from "../components/Footer";
import { Share2 } from "lucide-react";
import jsPDF from "jspdf";


const baseUrl = "http://localhost:5000";

// Helper to match colors
const getCategoryColor = (category) => {
    const cat = category?.toLowerCase();
    if (cat === 'gold') return 'bg-emerald-500 text-white';
    if (cat === 'Premium') return 'bg-blue-500 text-white';
    if (cat === 'silver') return 'bg-gray-500 text-white';
    return 'bg-gray-500 text-white';
};

const generateSchemePDF = async (scheme) => {
    const doc = new jsPDF("p", "mm", "a4");

    // ---- FONT FIX ----
    doc.setFont("helvetica", "normal");

    // Load image
    const imgResponse = await fetch(`${baseUrl}/${scheme.image}`);
    const imgBlob = await imgResponse.blob();
    const imgBase64 = await new Promise((resolve) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result);
        reader.readAsDataURL(imgBlob);
    });

    // ===== HEADER (Unchanged) =====
    doc.setFillColor(128, 0, 0);
    doc.rect(0, 0, 210, 35, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.text("MYCHITS – SCHEME DETAILS", 105, 20, { align: "center" });

    // ===== IMAGE (Unchanged) =====
    doc.addImage(imgBase64, "JPEG", 25, 45, 160, 75);

    // ===== CONTENT: FORM FORMAT =====
    
    // Configuration
    const startX = 25;      
    const startY = 130;    
    const colWidth1 = 85;  
    const colWidth2 = 75;  
    const rowHeight = 12;  
    
    // Helper function
    const drawFormRow = (index, label, value) => {
        const y = startY + (index * rowHeight);
        const xRight = startX + colWidth1 + colWidth2;

        // Horizontal Line
        doc.setDrawColor(200); 
        doc.setLineWidth(0.5);
        doc.line(startX, y + rowHeight, xRight, y + rowHeight);

        // Vertical Line
        doc.line(startX + colWidth1, y, startX + colWidth1, y + rowHeight);

        // Label
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(80); 
        doc.text(`${label}:`, startX + 3, y + 8);

        // Value
        doc.setFont("helvetica", "normal");
        doc.setTextColor(0); 
        // NOTE: Changed to "Rs." to fix the symbol display issue
        doc.text(String(value).replace('₹', 'Rs.'), startX + colWidth1 + 5, y + 8);
    };

    // Outer Border
    doc.setDrawColor(0); 
    doc.setLineWidth(1);
    const totalHeight = rowHeight * 5;
    doc.rect(startX, startY, colWidth1 + colWidth2, totalHeight);

    // Draw Rows
    // We pass the value directly, but the drawFormRow helper replaces '₹' with 'Rs.' just in case
    drawFormRow(0, "Loan Value", `Rs. ${scheme.chitValue}`);
    drawFormRow(1, "Monthly Installment", `Rs. ${scheme.installment}`);
    drawFormRow(2, "Duration", `${scheme.months} Months`);
    drawFormRow(3, "Members", scheme.members);
    drawFormRow(4, "Category", scheme.category);

    // ===== DESCRIPTION SECTION (FIXED SPACING) =====
       // ===== DESCRIPTION SECTION (FIXED SPACING & SYMBOLS) =====
    let descY = startY + totalHeight + 10;

    // Label
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text("Description:", startX, descY);

    // Box Calculations
    descY += 5;
    const boxWidth = colWidth1 + colWidth2;
    const boxPadding = 5; // Inner padding for text
    const boxHeight = 30; 

    // Draw Box Border
    doc.setDrawColor(200);
    doc.setLineWidth(0.5);
    doc.rect(startX, descY, boxWidth, boxHeight);

    // --- FIX STARTS HERE ---
    
    // 1. Get the raw description
    let rawDesc = scheme.description || "No description available";

    // 2. REPLACE ALL '₹' symbols with 'Rs.' using Regex
    // The /g flag ensures it replaces every occurrence in the text
    let cleanDesc = rawDesc.replace(/₹/g, "Rs.");

    // Text Wrapping Logic
    const maxTextWidth = boxWidth - (boxPadding * 2);
    
    // 3. Use the CLEANED text for the PDF
    const descLines = doc.splitTextToSize(cleanDesc, maxTextWidth);

    // --- FIX ENDS HERE ---

    // Draw Text
    // We add 'boxPadding' to X and Y to position it inside the box
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(descLines, startX + boxPadding, descY + boxPadding + 2);

    // ===== FOOTER =====
    doc.setFontSize(10);
    doc.setTextColor(120);
    doc.text(
        "Generated by MyChits | Trusted Chit Fund Management",
        105,
        290,
        { align: "center" }
    );

    doc.save(`MyChits_${scheme.category}_Scheme.pdf`);
};

export default function Home() {
    const [products, setProducts] = useState([]);

    const [showModal, setShowModal] = useState(false);
    const [selectedScheme, setSelectedScheme] = useState(null);
    const [customer, setCustomer] = useState({
        name: "",
        phone: ""
    });

    useEffect(() => {
        fetchChits();
    }, []);

    // Keep your existing download logic
    const handleDownload = async (imagePath, title) => {
        try {
            const response = await fetch(`${baseUrl}/${imagePath}`);
            const blob = await response.blob();
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.style.display = 'none';
            a.href = url;
            a.download = `${title || 'chit-image'}.jpg`;
            document.body.appendChild(a);
            a.click();
            window.URL.revokeObjectURL(url);
            document.body.removeChild(a);
        } catch (err) {
            console.error("Download failed", err);
            alert("Could not download image");
        }
    };

    const fetchChits = async () => {
        try {
            const res = await api.get("/chitgroup");
            setProducts(res.data);
        } catch (err) {
            console.error(err);
        }
    };

    const handleShare = (p) => {
        const shareText = `MyChits Scheme

Chit Value: ₹${p.chitValue}
Duration: ${p.months} Months
Members: ${p.members}
Category: ${p.category}

Check this scheme now 👇`;

        const shareData = {
            title: "MyChits Scheme",
            text: shareText,
            url: window.location.href,
        };

        if (navigator.share) {
            navigator.share(shareData);
        } else {
            navigator.clipboard.writeText(
                `${shareText}\n${window.location.href}`
            );
            alert("Scheme details copied to clipboard");
        }
    };






    return (
        <div className="min-h-screen bg-[#F3F3F3F] text-gray-100 pb-20">

            {/* BEHANCE-STYLE HEADER */}
            <div className="max-w-7xl mx-auto px-6 py-20 text-center">
                <h1 className="text-5xl md:text-7xl font-extrabold text-white mb-4 tracking-tighter">
                    Chit <span className="text-blue-500">Gallery</span>
                </h1>
                <p className="text-gray-400 text-lg max-w-2xl mx-auto">
                    Explore premium financial schemes designed for growth. A curated collection of opportunities.
                </p>
            </div>

            {/* MASONRY GRID (Pinterest/Behance Style) */}
            <div className="max-w-7xl mx-auto px-6">
                <div className="columns-1 md:columns-2 lg:columns-3 gap-6 space-y-6">

                    {products.map((p) => {
                        const colorClass = getCategoryColor(p.category);

                        return (
                            <div key={p._id} className="break-inside-avoid relative group rounded-xl overflow-hidden cursor-pointer bg-[#404040] shadow-lg hover:shadow-2xl transition-all duration-300">


                                {/* 1. FULL IMAGE */}
                                <div className="relative w-full h-auto">
                                    <img
                                        src={`${baseUrl}/${p.image}`}
                                        alt="chit"
                                        className="w-full h-auto object-cover transition-transform duration-700 group-hover:scale-105"
                                    />

                                    {/* Category Badge (Top Right) */}
                                    <span className={`absolute top-4 right-4 px-3 py-1 text-xs font-bold uppercase tracking-widest rounded-md shadow-lg ${colorClass}`}>
                                        {p.category}
                                    </span>
                                    {/* SHARE BUTTON */}



                                    {/* Dark Overlay (Appears on Hover) */}
                                    <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/50 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex flex-col justify-end p-6">

                                        {/* Price Overlay */}
                                        <h3 className="text-3xl font-bold text-white mb-1 translate-y-4 group-hover:translate-y-0 transition-transform duration-300">
                                            ₹ {p.chitValue}
                                        </h3>

                                        {/* Details Row Overlay */}
                                        <div className="flex items-center justify-between text-gray-300 text-sm font-medium translate-y-4 group-hover:translate-y-0 transition-transform duration-300 delay-75">

                                            <div className="flex gap-4">
                                                <span className="flex items-center gap-1">
                                                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                                                    {p.months} Mos
                                                </span>
                                                <span className="flex items-center gap-1">
                                                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" /></svg>
                                                    {p.members} Mem
                                                </span>

                                                <button
                                                    onClick={(e) => {
                                                        e.stopPropagation();
                                                        handleShare(p);
                                                    }}
                                                    className="absolute  right-14 bg-blue-500 backdrop-blur p-2 rounded-full shadow hover:bg-blue-500 hover:text-white transition"
                                                    title="Share scheme"
                                                >
                                                    <Share2 size={16} />
                                                </button>


                                            </div>



                                            {/* Download Action */}
                                            <button
                                                onClick={(e) => {
                                                    e.stopPropagation();
                                                    setSelectedScheme(p);
                                                    setShowModal(true);
                                                }}
                                                className="bg-white text-black p-2 rounded-full hover:bg-emerald-400 transition-colors"
                                                title="Download Image"
                                            >
                                                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                                                        d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                                                </svg>
                                            </button>


                                        </div>
                                    </div>

                                </div>
                            </div>
                        );
                    })}
                </div>
            </div>

            {products.length === 0 && (
                <div className="text-center py-20 text-gray-500">
                    <p className="text-lg">No schemes available yet.</p>
                </div>
            )}


            {showModal && (
                <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 px-4">
                    <div className="bg-white rounded-2xl shadow-2xl w-full max-w-3xl overflow-hidden grid grid-cols-1 md:grid-cols-2">

                        {/* LEFT SIDE – MYCHITS INFO */}
                        <div className="bg-gradient-to-br from-blue-600 to-blue-500 text-white p-8 flex flex-col justify-between">
                            <div>
                                <h2 className="text-3xl font-extrabold mb-3">
                                    My<span className="text-yellow-300">Chits</span>
                                </h2>

                                <p className="text-blue-100 mb-6">
                                    Smart & secure chit fund schemes designed for your financial growth.
                                </p>

                                {selectedScheme && (
                                    <div className="bg-white/10 rounded-xl p-4 space-y-2">
                                        <p className="text-sm text-blue-100">Selected Scheme</p>
                                        <h3 className="text-2xl font-bold">
                                            ₹ {selectedScheme.chitValue}
                                        </h3>

                                        <div className="flex gap-4 text-sm text-blue-100 mt-2">
                                            <span>{selectedScheme.months} Months</span>
                                            <span>{selectedScheme.members} Members</span>
                                        </div>

                                        <span className="inline-block mt-3 px-3 py-1 text-xs font-semibold bg-yellow-400 text-blue-900 rounded-full">
                                            {selectedScheme.category}
                                        </span>
                                    </div>
                                )}
                            </div>

                            <div className="mt-8 text-xs text-blue-100 space-y-1">
                                <p>✔ Trusted chit management</p>
                                <p>✔ Transparent & secure process</p>
                                <p>✔ Local support & guidance</p>
                            </div>
                        </div>

                        {/* RIGHT SIDE – FORM */}
                        <div className="p-8 text-black">
                            <h3 className="text-2xl font-bold mb-2">
                                Download Scheme
                            </h3>

                            <p className="text-gray-500 text-sm mb-6">
                                Enter your details to download the scheme image
                            </p>

                            <input
                                type="text"
                                placeholder="Your Name"
                                className="w-full border border-gray-300 p-3 rounded-lg mb-4 focus:outline-none focus:ring-2 focus:ring-blue-500"
                                value={customer.name}
                                onChange={(e) =>
                                    setCustomer({ ...customer, name: e.target.value })
                                }
                            />

                            <input
                                type="tel"
                                placeholder="Phone Number"
                                className="w-full border border-gray-300 p-3 rounded-lg mb-6 focus:outline-none focus:ring-2 focus:ring-blue-500"
                                value={customer.phone}
                                onChange={(e) =>
                                    setCustomer({ ...customer, phone: e.target.value })
                                }
                            />

                            <div className="flex gap-3">
                                <button
                                    onClick={() => setShowModal(false)}
                                    className="w-1/2 py-3 rounded-lg bg-gray-200 hover:bg-gray-300 transition"
                                >
                                    Cancel
                                </button>

                                <button
                                    onClick={async () => {
                                        if (!customer.name || !customer.phone) {
                                            alert("Please enter name and phone");
                                            return;
                                        }

                                        try {
                                            await api.post("/leads/create", {
                                                name: customer.name,
                                                phone: customer.phone,
                                                schemeId: selectedScheme._id,
                                            });

                                            await generateSchemePDF(selectedScheme);

                                            setCustomer({ name: "", phone: "" });
                                            setShowModal(false);
                                        } catch (err) {
                                            console.error(err);
                                            alert("Failed to save lead");
                                        }
                                    }}
                                    className="w-1/2 py-3 rounded-lg bg-blue-600 text-white font-semibold hover:bg-blue-700 transition"
                                >
                                    Submit & Download PDF
                                </button>

                            </div>

                            <p className="text-xs text-gray-400 mt-4">
                                We respect your privacy. Your details are safe with us.
                            </p>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}